kind: Service
apiVersion: v1
metadata:
  name: sample-web-kustomize
spec:
  selector:
    app: sample-web-kustomize
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8100
    targetPort: 5000
